name: Lint

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv python install
      - run: uv sync --all-extras --locked --dev
      - run: uv run ruff check .
      - run: uv run ruff format --check .
